_target_: networks.graph_encoder.gnn.Multi_GNN
_recursive_: false

input_dim: {} # Set during runtime
hidden_dim: 512
output_dim: 512
edge_dim: 0 # Set during runtime
num_layer: 2
layer_name: "GATv2"
pool_name: "mean" # mean, max, sum
heads: 4
dropout: 0.3
modalities: ${manager.graph_modalities}